name: Production deploy

on:
  push:
    branches:
      - main
jobs:
  Deploy-Production:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Vercel deploy
      uses: amondnet/vercel-action@v20 #deploy
      with:
        vercel-token: ${{ secrets.VERCEL_TOKEN }} # Required
        github-token: ${{ secrets.GITHUB_TOKEN }} #Optional 
        vercel-args: '--prod' #Production deploy
        vercel-org-id: ${{ secrets.ORG_ID}}  #Required
        vercel-project-id: ${{ secrets.PROJECT_ID}} #Required 